* Reading notes from Matt Sciandra's Jan 11, 2016 documentation
  1. [X] We should enquire as to any specific problems expected when running this code on SAS v9.4
  2. [ ] Redoing the imputation w/ and w/o tract clustering will make interesting comparison
  3. [ ] Align our paper's terminology with Mr. Sciandra's p. 5: /LPV/, /TRV/, /control/
  4. [ ] Ensure alignment where necessary as well with the collection-phase terms on pp. 5-6
  5. [ ] Check the weighted response rate (90.0%) vs JAMA paper; I recall something in the 80s
  6. [ ] The imputation described in Section 4.2 is truly remarkable:
     - fully 22% (absolute count) of the imputed individuals were completely made up!
     - (TODO: calculate this figure on a weighted basis, also)
     - How could anyone expect this to do anything but magnify RNG errors?
     - [ ] **This makes an interviewed-case (NB, /not/ 'complete-case') analysis essential**
     - [ ] **Changing the imputation seed is also essential**
  7. Our paper must anticipate and circumvent the original authors' potential misuse of 'false discovery rate' as a defense against our argument.

* Notes after our first successful end-to-end run of run_me.sas
  1. [ ] Prepend the original coefficients as first of the 10,000 betas_posterior_samples
  2. [ ] Check that the initial OR and its CI match the JAMA paper
  3. [ ] Backtrack to find out why they didn't P-^(
     It seems almost inevitable that /something/ will cause a mismatch, whether this a mismatched
     selection of random seed, or some other problem.
  4. [ ] Investigate whether M3 can be installed _easily_ from USB (i.e., w/o Internet)
  5. [ ] Implement a passable age distribution comparison overlay graphic
  6. [ ] Implement a passable UpperCL & LowerCL bootstrap density graphic
  7. [ ] Fix whatever problem we found in step #3 above
  8. [ ] If SAS graphics are unsuitable for publication, make R versions of them
  9. [ ] Work out a scheme for version control on the _logs_
  10. [ ] Inspect the logs closely for WARNINGs
